# NodePort para poder probar la API desde el navegador/Postman en
# http://<IP_PUBLICA_EC2>:30080/usuarios. El Security Group de la instancia
# EC2 debe tener abierto el rango 30000-32767 (ver docs/).
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
  namespace: devops-usuarios
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
